/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendamentoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author loren
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendamentoController controller;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendamentoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToggleButtonAgendamento = new javax.swing.JToggleButton();
        LabelObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaObservacao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        TextFieldHora = new javax.swing.JTextField();
        LabelData = new javax.swing.JLabel();
        TextFieldData = new javax.swing.JTextField();
        TextPesagem = new javax.swing.JTextField();
        LabelPesagem = new javax.swing.JLabel();
        LabelServico = new javax.swing.JLabel();
        ComboBoxServico = new javax.swing.JComboBox<>();
        LabelBaseSaida = new javax.swing.JLabel();
        ComboBoxBaseSaida = new javax.swing.JComboBox<>();
        LabelBaseEntrada = new javax.swing.JLabel();
        ComboBoxBaseEntrada = new javax.swing.JComboBox<>();
        LabelEmpresa = new javax.swing.JLabel();
        JTextEmpresa = new javax.swing.JTextField();
        LabeliD = new javax.swing.JLabel();
        TextFieldcnpj = new javax.swing.JTextField();
        LabelFundoPretoAgenda = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        LabelFundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToggleButtonAgendamento.setBackground(new java.awt.Color(102, 255, 102));
        ToggleButtonAgendamento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ToggleButtonAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        ToggleButtonAgendamento.setText("Agendar");
        ToggleButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButtonAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(ToggleButtonAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 330, 40));

        LabelObservacao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        LabelObservacao.setText("Observação: ");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        TextAreaObservacao.setColumns(20);
        TextAreaObservacao.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        TextAreaObservacao.setRows(5);
        jScrollPane1.setViewportView(TextAreaObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 330, 330));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, -1, -1));

        TextFieldHora.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        getContentPane().add(TextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 300, 40));

        LabelData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Data:");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        TextFieldData.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        TextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 300, 40));

        TextPesagem.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        TextPesagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPesagemActionPerformed(evt);
            }
        });
        getContentPane().add(TextPesagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 300, 40));

        LabelPesagem.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelPesagem.setForeground(new java.awt.Color(255, 255, 255));
        LabelPesagem.setText("Pesagem KG:");
        getContentPane().add(LabelPesagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        LabelServico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelServico.setForeground(new java.awt.Color(255, 255, 255));
        LabelServico.setText("Serviço:");
        getContentPane().add(LabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        ComboBoxServico.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        ComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KronoLog", "KronoDrive" }));
        ComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 300, 40));

        LabelBaseSaida.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelBaseSaida.setForeground(new java.awt.Color(255, 255, 255));
        LabelBaseSaida.setText("Base de saída:");
        getContentPane().add(LabelBaseSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        ComboBoxBaseSaida.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        ComboBoxBaseSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base Bandeirantes", "Base Machado de Assis", "Base Candango", "Base Corumbá", "Base Pelourinho", "Base Frevo", "Base Dragão do Mar", "Base Tingui", " " }));
        ComboBoxBaseSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBaseSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxBaseSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 300, 40));

        LabelBaseEntrada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelBaseEntrada.setForeground(new java.awt.Color(255, 255, 255));
        LabelBaseEntrada.setText("Base de entrada:");
        getContentPane().add(LabelBaseEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        ComboBoxBaseEntrada.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        ComboBoxBaseEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base Bandeirantes", "Base Machado de Assis", "Base Candango", "Base Corumbá", "Base Pelourinho", "Base Frevo", "Base Dragão do Mar", "Base Tingui", " " }));
        ComboBoxBaseEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBaseEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxBaseEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 40));

        LabelEmpresa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        LabelEmpresa.setText("Empresa:");
        getContentPane().add(LabelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 20));

        JTextEmpresa.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        JTextEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(JTextEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 300, 40));

        LabeliD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabeliD.setForeground(new java.awt.Color(255, 255, 255));
        LabeliD.setText("CNPJ:");
        getContentPane().add(LabeliD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        TextFieldcnpj.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        TextFieldcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldcnpjActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 300, 40));

        LabelFundoPretoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(LabelFundoPretoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 1000, 630));

        jButtonVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        LabelFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(LabelFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextEmpresaActionPerformed

    private void ComboBoxBaseEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBaseEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxBaseEntradaActionPerformed

    private void ToggleButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButtonAgendamentoActionPerformed
   
            controller.salvaAgendamento();
        limparCampos();
    }//GEN-LAST:event_ToggleButtonAgendamentoActionPerformed

    private void TextFieldcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldcnpjActionPerformed

    private void ComboBoxBaseSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBaseSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxBaseSaidaActionPerformed

    private void ComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxServicoActionPerformed

    private void TextPesagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPesagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPesagemActionPerformed

    private void TextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDataActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuPrincipal telaMenuPrincipal = new MenuPrincipal();
        telaMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    public JComboBox<String> getComboBoxBaseSaida() {
        return ComboBoxBaseSaida;
    }

    public void setComboBoxBaseSaida(JComboBox<String> ComboBoxBaseSaida) {
        this.ComboBoxBaseSaida = ComboBoxBaseSaida;
    }

    public JComboBox<String> getComboBoxServico() {
        return ComboBoxServico;
    }

    public void setComboBoxServico(JComboBox<String> ComboBoxServico) {
        this.ComboBoxServico = ComboBoxServico;
    }

    public JLabel getLabelBaseEntrada() {
        return LabelBaseEntrada;
    }

    public void setLabelBaseEntrada(JLabel LabelBaseEntrada) {
        this.LabelBaseEntrada = LabelBaseEntrada;
    }

    public JLabel getLabelBaseSaida() {
        return LabelBaseSaida;
    }

    public JComboBox<String> getComboBoxBaseEntrada() {
        return ComboBoxBaseEntrada;
    }

    public void setComboBoxBaseEntrada(JComboBox<String> ComboBoxBaseEntrada) {
        this.ComboBoxBaseEntrada = ComboBoxBaseEntrada;
    }
    
    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
    public void setLabelBaseSaida(JLabel LabelBaseSaida) {
        this.LabelBaseSaida = LabelBaseSaida;
    }

    public JLabel getLabelData() {
        return LabelData;
    }

    public void setLabelData(JLabel LabelData) {
        this.LabelData = LabelData;
    }

    public JLabel getLabelEmpresa() {
        return LabelEmpresa;
    }

    public void setLabelEmpresa(JLabel LabelEmpresa) {
        this.LabelEmpresa = LabelEmpresa;
    }

    public JLabel getLabelFundoAgenda() {
        return LabelFundoAgenda;
    }

    public void setLabelFundoAgenda(JLabel LabelFundoAgenda) {
        this.LabelFundoAgenda = LabelFundoAgenda;
    }

    public JLabel getLabelFundoPretoAgenda() {
        return LabelFundoPretoAgenda;
    }

    public void setLabelFundoPretoAgenda(JLabel LabelFundoPretoAgenda) {
        this.LabelFundoPretoAgenda = LabelFundoPretoAgenda;
    }

    public JLabel getLabelObservacao() {
        return LabelObservacao;
    }

    public void setLabelObservacao(JLabel LabelObservacao) {
        this.LabelObservacao = LabelObservacao;
    }

    public JLabel getLabelPesagem() {
        return LabelPesagem;
    }

    public void setLabelPesagem(JLabel LabelPesagem) {
        this.LabelPesagem = LabelPesagem;
    }

    public JLabel getLabelServico() {
        return LabelServico;
    }

    public void setLabelServico(JLabel LabelServico) {
        this.LabelServico = LabelServico;
    }

    public JLabel getLabeliD() {
        return LabeliD;
    }

    public void setLabeliD(JLabel LabeliD) {
        this.LabeliD = LabeliD;
    }

    public JTextArea getTextAreaObservacao() {
        return TextAreaObservacao;
    }

    public void setTextAreaObservacao(JTextArea TextAreaObservacao) {
        this.TextAreaObservacao = TextAreaObservacao;
    }

    public JTextField getTextFieldData() {
        return TextFieldData;
    }

    public void setTextFieldData(JTextField TextFieldData) {
        this.TextFieldData = TextFieldData;
    }

    public JTextField getTextFieldHora() {
        return TextFieldHora;
    }

    public void setTextFieldHora(JTextField TextFieldHora) {
        this.TextFieldHora = TextFieldHora;
    }

    public JTextField getTextFieldcnpj() {
        return TextFieldcnpj;
    }

    public void setTextFieldcnpj(JTextField TextFieldcnpj) {
        this.TextFieldcnpj = TextFieldcnpj;
    }

    public JTextField getTextPesagem() {
        return TextPesagem;
    }

    public void setTextPesagem(JTextField TextPesagem) {
        this.TextPesagem = TextPesagem;
    }

    public JToggleButton getToggleButtonAgendamento() {
        return ToggleButtonAgendamento;
    }

    public void setToggleButtonAgendamento(JToggleButton ToggleButtonAgendamento) {
        this.ToggleButtonAgendamento = ToggleButtonAgendamento;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getJTextEmpresa() {
        return JTextEmpresa;
    }

    public void setJTextEmpresa(JTextField JTextEmpresa) {
        this.JTextEmpresa = JTextEmpresa;
    }
    private void limparCampos() {
        // Limpar campos de texto
        TextFieldHora.setText("");
        TextFieldData.setText("");
        TextPesagem.setText("");
        JTextEmpresa.setText("");
        TextFieldcnpj.setText("");
        TextAreaObservacao.setText("");

        // Redefinir seleção dos JComboBox
        ComboBoxServico.setSelectedIndex(0);
        ComboBoxBaseSaida.setSelectedIndex(0);
        ComboBoxBaseEntrada.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBaseEntrada;
    private javax.swing.JComboBox<String> ComboBoxBaseSaida;
    private javax.swing.JComboBox<String> ComboBoxServico;
    private javax.swing.JTextField JTextEmpresa;
    private javax.swing.JLabel LabelBaseEntrada;
    private javax.swing.JLabel LabelBaseSaida;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelEmpresa;
    private javax.swing.JLabel LabelFundoAgenda;
    private javax.swing.JLabel LabelFundoPretoAgenda;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelPesagem;
    private javax.swing.JLabel LabelServico;
    private javax.swing.JLabel LabeliD;
    private javax.swing.JTextArea TextAreaObservacao;
    private javax.swing.JTextField TextFieldData;
    private javax.swing.JTextField TextFieldHora;
    private javax.swing.JTextField TextFieldcnpj;
    private javax.swing.JTextField TextPesagem;
    private javax.swing.JToggleButton ToggleButtonAgendamento;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
