/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author loren
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() { 
        initComponents();
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonTelaLogin = new javax.swing.JButton();
        TextSenha = new javax.swing.JPasswordField();
        TextEmail = new javax.swing.JTextField();
        jLabelTextSenha = new javax.swing.JLabel();
        jLabelTextLogin = new javax.swing.JLabel();
        jLabelTextEmail = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoLogin = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonTelaLogin.setBackground(new java.awt.Color(102, 102, 102));
        ButtonTelaLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonTelaLogin.setText("Entrar");
        ButtonTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTelaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 260, -1));

        TextSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 260, 50));

        TextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 260, 50));

        jLabelTextSenha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextSenha.setText("Senha");
        getContentPane().add(jLabelTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        jLabelTextLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTextLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextLogin.setText("Login");
        getContentPane().add(jLabelTextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        jLabelTextEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTextEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextEmail.setText("Email");
        getContentPane().add(jLabelTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jButtonVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 90, 30));

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/painel-login.png"))); // NOI18N
        jLabelFundoLogin.setText("eknkefc");
        getContentPane().add(jLabelFundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 550, 540));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/krono login.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaActionPerformed

    private void ButtonTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTelaLoginActionPerformed

  
        try {
            //Executa quando clico no botão
            controller.autenticar();
                   
        } catch (SQLException ex) {
            
        }

    }//GEN-LAST:event_ButtonTelaLoginActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuPrincipal telaMenuPrincipal = new MenuPrincipal();
        telaMenuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /*public JLabel getjLabelTextEmail() {
        return jLabelTextEmail;
    }

    public void setjLabelTextEmail(JLabel jLabelTextEmail) {
        this.jLabelTextEmail = jLabelTextEmail;
    }

    public JLabel getjLabelTextSenha() {
        return jLabelTextSenha;
    }

    public void setjLabelTextSenha(JLabel jLabelTextSenha) {
        this.jLabelTextSenha = jLabelTextSenha;
    }*/

    public JTextField getTextEmail() {
        return TextEmail;
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTelaLogin;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelTextEmail;
    private javax.swing.JLabel jLabelTextLogin;
    private javax.swing.JLabel jLabelTextSenha;
    // End of variables declaration//GEN-END:variables

   

 
}
